version: 0.2

env:
  variables:
    PLATFORM: "centos7"
    SRV_TYPE: "centos7_dev"
    EBS_VOLUME_SIZE: "100"


phases:
  install:
    commands:
#      - curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.SecretAccessKey , .Token ,.AccessKeyId'
#      - echo "------env------" ; env | sort ; echo "------env------"
      - bash -c 'aws_var=(AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID); for i in $(curl -s 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r ".SecretAccessKey , .Token ,.AccessKeyId"); do  echo "export ${aws_var[@]:0:1}=$i" >> c_env; aws_var=("${aws_var[@]:1}"); done ;'
      - source ./c_env
      - echo "------------env------------" ; env | grep AWS | sort ; echo "------------env------------"
  pre_build:
    commands:
      - terraform -v ; packer -v ; ansible --version ; aws --version

  build:
    commands:
      - bash -c 'export USER=root ; packer build -color=false -machine-readable -var "srcver=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}" -var "ebs_volume_size=${EBS_VOLUME_SIZE}" ${PLATFORM}.json | tee build.log'
        
  post_build:
    commands:
      - echo build completed on `date`

artifacts:
  files:
    - manifest.json
